// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIInvalidResponse Api invalid response
//
// swagger:model ApiInvalidResponse
type APIInvalidResponse struct {

	// code
	Code int64 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this Api invalid response
func (m *APIInvalidResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api invalid response based on context it is used
func (m *APIInvalidResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIInvalidResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIInvalidResponse) UnmarshalBinary(b []byte) error {
	var res APIInvalidResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
