// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Data data
//
// swagger:model Data
type Data struct {

	// alias
	Alias []string `json:"alias"`

	// city
	City string `json:"city,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// coordinates
	Coordinates []float64 `json:"coordinates"`

	// country
	Country string `json:"country,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// province
	Province string `json:"province,omitempty"`

	// regions
	Regions []string `json:"regions"`

	// timezone
	Timezone string `json:"timezone,omitempty"`

	// unlocs
	Unlocs []string `json:"unlocs"`
}

// Validate validates this data
func (m *Data) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this data based on context it is used
func (m *Data) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Data) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Data) UnmarshalBinary(b []byte) error {
	var res Data
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
